apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ceramic-one
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ceramic-one
  serviceName: ceramic-one
  template:
    metadata:
      labels:
        app: ceramic-one
    spec:
      containers:
        - name: ceramic-one
          envFrom:
            - configMapRef:
                name: ceramic-one-env
          image: ceramicnetwork/ceramic-one
          imagePullPolicy: Always
          ports:
            - containerPort: 4101
              name: swarm-tcp
              protocol: TCP
            - containerPort: 5101
              name: rpc
              protocol: TCP
            - containerPort: 9465
              name: metrics
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ceramic/liveness
              port: rpc
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /ceramic/liveness
              port: rpc
              scheme: HTTP
          resources:
            limits:
              cpu: "1"
              ephemeral-storage: 1Gi
              memory: 1Gi
            requests:
              cpu: "1"
              ephemeral-storage: 1Gi
              memory: 1Gi
          volumeMounts:
            - mountPath: /data/ceramic-one
              name: ceramic-one-data
      volumes:
        - name: ceramic-one-data
          persistentVolumeClaim:
            claimName: ceramic-one-pvc
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: ceramic-one-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ceramic-one
spec:
  ports:
    - name: swarm-tcp
      port: 4101
      protocol: TCP
      targetPort: swarm-tcp
    - name: rpc
      port: 5101
      protocol: TCP
      targetPort: rpc
    - name: metrics
      port: 9465
      protocol: TCP
      targetPort: metrics
  selector:
    app: ceramic-one
---
apiVersion: v1
kind: Service
metadata:
  name: ceramic-one-0
spec:
  ports:
    - name: swarm-tcp
      port: 4101
      protocol: TCP
      targetPort: swarm-tcp
    - name: rpc
      port: 5101
      protocol: TCP
      targetPort: rpc
    - name: metrics
      port: 9465
      protocol: TCP
      targetPort: metrics
  selector:
    app: ceramic-one
    statefulset.kubernetes.io/pod-name: ceramic-one-0
---
apiVersion: v1
kind: Service
metadata:
  name: ceramic-one-1
spec:
  ports:
    - name: swarm-tcp
      port: 4101
      protocol: TCP
      targetPort: swarm-tcp
    - name: rpc
      port: 5101
      protocol: TCP
      targetPort: rpc
    - name: metrics
      port: 9465
      protocol: TCP
      targetPort: metrics
  selector:
    app: ceramic-one
    statefulset.kubernetes.io/pod-name: ceramic-one-1
