apiVersion: v1
kind: Service
metadata:
  name: ceramic-one-lb-0
  annotations:
    cloud.google.com/l4-rbs: "enabled"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: ceramic-one
    statefulset.kubernetes.io/pod-name: ceramic-one-0
  ports:
  - name: swarm-tcp
    protocol: TCP
    port: 4101
    targetPort: 4101
---
apiVersion: v1
kind: Service
metadata:
  name: ceramic-one-lb-1
  annotations:
    cloud.google.com/l4-rbs: "enabled"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: ceramic-one
    statefulset.kubernetes.io/pod-name: ceramic-one-1
  ports:
  - name: swarm-tcp
    protocol: TCP
    port: 4101
    targetPort: 4101
