apiVersion: v1
kind: Service
metadata:
  name: js-ceramic-lb-0
  annotations:
    cloud.google.com/l4-rbs: "enabled"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: js-ceramic
    statefulset.kubernetes.io/pod-name: js-ceramic-0
  ports:
  - name: api
    protocol: TCP
    port: 7007
    targetPort: 7007
---
apiVersion: v1
kind: Service
metadata:
  name: js-ceramic-lb-1
  annotations:
    cloud.google.com/l4-rbs: "enabled"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: js-ceramic
    statefulset.kubernetes.io/pod-name: js-ceramic-1
  ports:
  - name: api
    protocol: TCP
    port: 7007
    targetPort: 7007