apiVersion: v1
kind: Service
metadata:
  name: composedb
  namespace: ceramic-one
  labels:
    app: composedb
spec:
  ports:
    - name: composedb
      protocol: TCP
      port: 7007
      targetPort: 7007
  selector:
    app: composedb
  type: ClusterIP

