apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: composedb-ingress
  namespace: ceramic-one
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - "your-domain.com"  # Replace with your actual domain
    secretName: ceramic-tls-secret
  rules:
  - host: "your-domain.com"  # Replace with your actual domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: composedb
            port:
              number: 7007
